services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://potluck:potluck@db:5432/potluck # pragma: allowlist secret
      SECRET_KEY: thisisnotasecrectkey
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - db

  db:
    image: "postgres:13"
    expose:
      - 5432
    environment:
      POSTGRES_USER: potluck
      POSTGRES_PASSWORD: potluck
