services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://potluck:potluck@db:5432/potluck # pragma: allowlist secret
      SECRET_KEY: thisisnotasecrectkey
      DJANGO_SETTINGS_MODULE: potluck.settings.base
      DEBUG: "True"
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - db

  db:
    image: "postgres:13"
    expose:
      - 5432
    environment:
      POSTGRES_USER: potluck
      POSTGRES_PASSWORD: potluck
