# Generated by Django 3.2.9 on 2021-11-23 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0010_default_tiebreaker_description'),
        ('games', '0003_add_pot_fk_to_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='pots.pot'),
        ),
    ]
