# Generated by Django 3.2.9 on 2021-11-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_non_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_tie",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
