# Generated by Django 3.2.9 on 2021-12-04 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_order_teams_by_name"),
        ("games", "0005_game_is_tie"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="away_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="home_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="teams.team",
            ),
        ),
    ]
