# Generated by Django 3.1.4 on 2021-06-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pots", "0001_add_pot_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="pot",
            name="status",
            field=models.CharField(
                choices=[
                    ("DR", "Draft"),
                    ("OP", "Open"),
                    ("CL", "Closed"),
                    ("TA", "Tally"),
                ],
                default="DR",
                max_length=2,
            ),
        ),
    ]
