# Generated by Django 3.2.6 on 2021-11-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pots", "0003_pick_sheet_picker_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="pot",
            name="tiebreaker_score",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
