# Generated by Django 3.2.6 on 2021-11-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pots", "0005_alter_pot_tiebreaker_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pot",
            name="tiebreaker_score",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Enter the tiebreaker score.", null=True
            ),
        ),
    ]
