# Generated by Django 3.2.6 on 2021-11-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pots", "0006_allow_blank_tiebreaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="pot",
            name="tiebreaker_description",
            field=models.CharField(
                help_text='Describe the type of tiebreaker you want to use for the pot. For example: "Total score of the Monday night game"',
                max_length=500,
                null=True,
            ),
        ),
    ]
