# Generated by Django 3.2.6 on 2021-11-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pots", "0007_pot_tiebreaker_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pot",
            name="tiebreaker_score",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Enter the score for the tiebreaker.", null=True
            ),
        ),
    ]
