# Generated by Django 3.2.6 on 2021-11-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pots", "0008_update_help_text_for_tiebreaker_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pot",
            name="tiebreaker_description",
            field=models.CharField(
                help_text='Describe the tiebreaker score you want to use for the pot. For example: "Total score of the Monday night game". In case of a tie, the submission with the closest guess to the score wins.',
                max_length=500,
                null=True,
            ),
        ),
    ]
