# Generated by Django 3.1.4 on 2021-04-03 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0003_add_pot_fk_to_game"),
        ("teams", "0001_add_team_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePick",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_picks",
                        to="games.game",
                    ),
                ),
                (
                    "pick",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
