# Generated by Django 3.1.4 on 2021-05-23 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picks", "0002_add_pick_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamepick",
            name="pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_picks",
                to="picks.pick",
            ),
        ),
    ]
