# Generated by Django 3.1.4 on 2021-05-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0001_add_pot_model'),
        ('picks', '0004_rename_game_pick_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pick',
            new_name='PickSheet',
        ),
    ]
