# Generated by Django 3.1.4 on 2021-05-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_add_pot_fk_to_game'),
        ('teams', '0001_add_team_model'),
        ('picks', '0005_rename_pick_to_picksheet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamePickTemp',
            new_name='Pick',
        ),
    ]
