# Generated by Django 3.1.4 on 2021-05-24 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_add_pot_fk_to_game'),
        ('picks', '0007_rename_pick_pick_to_pick_picksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='games.game'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='pick_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='picks.picksheet'),
        ),
    ]
