# Generated by Django 3.1.4 on 2021-05-24 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0001_add_pot_model'),
        ('picks', '0008_rename_game_pick_relation_on_game_and_pick_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picksheet',
            name='pot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_sheets', to='pots.pot'),
        ),
    ]
