# Generated by Django 3.2.6 on 2021-11-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picks", "0011_picksheet_tiebreaker_guess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picksheet",
            name="picker",
            field=models.CharField(
                help_text="Enter the name of the person submitting this pick sheet.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="picksheet",
            name="tiebreaker_guess",
            field=models.PositiveSmallIntegerField(
                help_text="Enter your guess for the tiebreaker score.", null=True
            ),
        ),
    ]
