# Generated by Django 3.2.6 on 2021-11-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picks", "0012_pick_sheet_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picksheet",
            name="tiebreaker_guess",
            field=models.PositiveSmallIntegerField(
                help_text="Enter your guess for the tiebreaker.", null=True
            ),
        ),
    ]
